// global variable definitions to store sensor readings and data
float hum;  
float temp; 
float cm; 
int smoke;
String DATA;
int waterPresent = 0 ;
int flameValue=0;
int ultrasonic;
boolean open;
// used to stop test when finished or failed
boolean test;
void setup()
{
  // intalize serial to print the results 
  Serial.begin(9600);
  open = true;
  // set test to true to start testing
  test = true;
}
void loop()
{
  while (test){ // start testing
    Serial.println("Starting test 1/5: testcheckDataThresholdsNormal");
    if (testcheckDataThresholdsNormal()){
      Serial.println("PASS");
      }
     else {Serial.println("FAIL"); test=false; break;} // test failed stop
     Serial.println("Starting test 2/5: testcreateAndFormatData");
    if (testcreateAndFormatData()){
      Serial.println("PASS");
      }
     else {Serial.println("FAIL"); test=false; break;}
     Serial.println("Starting test 3/5: testcheckDataThresholdsHighTemp");
    if (testcheckDataThresholdsHighTemp()){
      Serial.println("PASS");
      }
     else {Serial.println("FAIL"); test=false; break;}
     Serial.println("Starting test 4/5: testsendAlarm");
     String alarmType = checkDataThresholds();  
     if (testsendAlarm(alarmType)){
      Serial.println("PASS");
      }
     else {Serial.println("FAIL"); test=false; break;}
     Serial.println("Starting test 5/5: testcheckDataThresholdLowTemp");
     if (testcheckDataThresholdLowTemp()){
      Serial.println("PASS");
      Serial.println("ALL TESTS PASSED");
      test=false;
      }
     else {Serial.println("FAIL"); test=false; break;}
  }
}

// test the checkdata thresholds method with normal values "no thresholds crossed"
boolean testcheckDataThresholdsNormal(){
    getFlame(0);
    getSmoke(0);
    getWater(0);
    getTempAndHum(24,20);
    getUltrasonic(20);
    String result = checkDataThresholds();
    if (result != "" ){
      return false; // test failed function return values is not empty
      }
    return true;
}
// test the checkdata thresholds method with temp high threshold crossed
boolean testcheckDataThresholdsHighTemp(){
    getFlame(0);
    getSmoke(0);
    getWater(0);
    getTempAndHum(80,20);
    getUltrasonic(20);
    String result = checkDataThresholds();
    if (result != "HIGHTEMP " ){
      return false; // test failed no alarm generated
      }
    return true;
}
// test the checkdata thresholds method with temp low threshold crossed
boolean testcheckDataThresholdLowTemp(){
    getFlame(0);
    getSmoke(0);
    getWater(0);
    getTempAndHum(-10,20);
    getUltrasonic(20);
    String result = checkDataThresholds();
    if (result != "LOWTEMP " ){
      return false; // test failed no alarm generated
    }
    return true;  
}

// test the creation and formatting of the data to send to the RPI
boolean testcreateAndFormatData(){
  createAndFormatData();
  if (DATA == String("{‘temp’:" + String(temp) + ", ‘humid’:" + String(hum) +  ", ‘flame’:"+ String(flameValue) +", ‘water’:"+ String(waterPresent) +", ‘smoke’ :" +String(smoke)+ ", ‘garage’:"+ "OPEN" +", ‘ultrasonic’:" +String(cm)+ "}")){
      return true ;
    }
    return false;
  }

// tests the send alarm method when an alarm is present, the alarm is generated by 
//previously calling checkthresholds when the global data has crossed a certian threshold
boolean testsendAlarm(String Alarmtype){
  sendAlarm(Alarmtype);
  if (DATA == String("{'alarm':"+ Alarmtype + "}")){
    return true;
    }
  else{return false;}
}

// stubs for fuctions responsible for reading sensor values

void getFlame(int val){
  flameValue = val;
}
void getSmoke(int val){
  smoke = val;
}
void getWater(int val){
  waterPresent = val;  
}
void getTempAndHum(int tempval, int humval){ // need a dealy of 2 seconds between calls 
    hum = humval;
    temp= tempval;
}
void getUltrasonic(int value){
    ultrasonic = value;
}

// functions under test start here, these are the functions used in the arduiono script

// checks dataThresholds and returns resulting alarm if any thresholds are crossed, returns empty string otherwise
String checkDataThresholds(){
  String alarm = "";
  if (smoke > 350){
    alarm = alarm +  "SMOKE ";}
  if (flameValue > 100){
    alarm = alarm  + "FLAME ";}  
  if (waterPresent > 0){
    alarm = alarm + " " + "WATER ";
    }
  if (temp > 42){
    alarm = alarm  + "HIGHTEMP ";
    }
  if (temp < 0) {
    alarm = alarm +  "LOWTEMP ";
    }
  if (hum > 80){
    alarm = alarm +  "HUMIDITY ";
    }
  return alarm;
  }
// creates the alarm to send to the RPI if a threshold is crossed
void sendAlarm(String Alarmtype){
  DATA=String("{'alarm':"+ Alarmtype + "}");
}

// creates and formats a string of data to send via serial port to RPI
void createAndFormatData(){
  String garageStr; 
  if (open){
    garageStr="OPEN";
  }
  else{garageStr="CLOSED";}
  DATA = String("{‘temp’:" + String(temp) + ", ‘humid’:" + String(hum) +  ", ‘flame’:"+ String(flameValue) +", ‘water’:"+ String(waterPresent) +", ‘smoke’ :" +String(smoke)+ ", ‘garage’:"+ garageStr +", ‘ultrasonic’:" +String(cm)+ "}"); 
}
